*  Modified in 2025 for RHEL 9 distro's (not for use on RHEL 8 or RHEL 10 <--yet) 
** The original author was https://github.com/penguin2716/autoinstall_cloudstack
: ****** THE WEBMIN INSTALL IS NOW AN OPTION IN THE SCRIPT DONT SELECT IT IF YOU HAVE NO USE FOR IT. ******

* What is this?

  This is an easy installation script for CloudStack 4.x.
  This script automates installation on a fresh CentOS 9.x node by using minimal install.
  All you have to do is running this script with options '-canm'.
  After a while you will see welcome message on the CloudStack web UI.

  This script also saves installation steps of CloudStack on multiple nodes
  with Management Servers, Computing Nodes and Storage Servers.

* How to use

  Download this script into wherever you like on the server that CloudStack will be installed.
  When you run this script with '-h'(help) optoin, you will see available options for the script.
  : ./autoinstall_cloudstack.sh -h

** Options
     | Option | Function                              |
     | -c     | install the common packages           |
     | -n     | install NFS server                    |
     | -a     | install the agent for computing nodes |
     | -m     | install the Management Server         |
     | -h     | show help                             |
     | -w     | install Webmin                        |
     | -r     | reboot after the installation         |
     | -u     | Uninstall CloudStack                  |
     Usage:
       - '-cm': when you want to install only the management server
       - '-cn': when you want to install only the NFS server
       - '-ca': when you want to install only the agent for computing nodes
     The '-c'(common) option will set SELinux to permissive, firewall and network.

     Installing CloudStack on single node, type command below:
     : bash autoinstall_cloudstack.sh -acnmwr

     Installing just the CloudStack Agent on a node, type command below:
     : bash autoinstall_cloudstack.sh -car

     Uninstalling cloudstack is still a work in progress but does a decent job of removing almost everything. During uninstall it will attempt to put the network as it was when installed...
     : ********* THIS PART IS NOT PERFECTED YET SO MAKE SURE TO HAVE REMOTE ACCESS TO THE BOX OTHER THEN SSH ********
     : bash autoinstall_cloudstack.sh -U

** Tips
  - You may need to install 'wget' or 'openssh-clients' package with yum command before downloading this script.
  - If you want to save time to input credentials to login by SSH, enter the ssh public key of your client machine to SSH_PUBLIC_KEY at the 3rd line of the script (optional).

* Concerns
  This script sets up the network for CloudStack requirements automatically, and it may works only on servers with 1 NIC. 

  This script sets up network bridges as:
  : # brctl show
  : bridge name     bridge id          STP enabled      interfaces
  : breno1-248    8000.c81f66e027dd       no            eno1.248
  :                                                        vnet14
  :                                                        vnet16
  : breno1-500    8000.c81f66e027dd       no            eno1.500
  :                                                        vnet26
  : cloud0        8000.fe00a9fe0e84       no            vnet0
  :                                                        vnet12
  :                                                        vnet27
  :                                                        vnet3
  : cloudbr0      8000.c81f66e027dd       yes           eno1
  :                                                        vnet1
  :                                                        vnet13
  :                                                        vnet2
  :                                                        vnet4
  :                                                        vnet5
  : cloudbr1      8000.000000000000       yes

* Steps to install CloudStack on single server
  - Install CentOS 9.X from the minimal.iso.
  - Install and configure CloudStack
    : yum install wget -y
    : wget https://raw.githubusercontent.com/siosios/autoinstall_cloudstack/main/autoinstall_cloudstack.sh
    : bash autoinstall_cloudstack.sh -acnmwr
  - Enter some informantion which is necessary for installation such as hostname and ip address.
  - The management server will be rebooted automatically. After rebooting,
    access "http://YOUR-MANAGEMENT-SERVER-IP:8080/client" by using web browser on a client machine.
  - Enter the username and password below.
    + username: admin
    + password: password
  - Enter the information of your cloud system through the Basic Installation Wizard.
  - *!DO NOT FORGET!* After creating a zone, reboot the SecondaryStorageVM.
  - Go to Infrastructure => System VMs => s-1-VM => click Reboot System VM button (icon of whirling arrow)
  - Go to Templates => CentOS 5.5 => Wait until "Ready" status changes from "" to "Yes".
